### ISSUE TITLE
Support Markdown in Changelog window

### ISSUE THREAD

**Issue by luzpaz** [antony-jr/AppImageUpdater#15]
![image](https://user-images.githubusercontent.com/4140247/62619078-e1fc3500-b8e3-11e9-9ee2-5973335323dc.png)

Note: Also notice that the title of the AppImage is truncated `FreeCAD_0`

Source AppImage: https://github.com/FreeCAD/FreeCAD/releases/tag/0.19_pre    
Using AppImageUpdater-ff9ee1f-x86_64.AppImage

![image](https://user-images.githubusercontent.com/4140247/62619291-65b62180-b8e4-11e9-922b-b3a6d7f7f138.png)

**Comment by luzpaz** [comment]
Really dig this updater. I like it way better than the official AppImage one. Any progress on this issue. It's a cosmetic thing that could get in the way of adoption, which would be a shame

**Comment by antony-jr** [comment]
> Really dig this updater. I like it way better than the official AppImage one.

@luzpaz Thank you.


> Any progress on this issue. It's a cosmetic thing that could get in the way of adoption, which would be a shame

Yes, I've been thinking about it... The problem is that there is no markdown parser in C++ that can parse github's style of markdown, since it supports both html mixed markdown we have to write our own markdown parser which supports partial html in C++. Its going to be tricky. The one of official examples in the docs implement this using QtWebEngine which I think is a overkill for an updater. **So I think if I have some time I might look for some other alternatives or write my own github flavored markdown parser**.

**EDIT**:

> Note: Also notice that the title of the AppImage is truncated FreeCAD_0

To solve this I have to use libappimage or role my own code to extract the desktop file from the AppImage and the icon too.. The desktop file can give a concise name of the program rather than the file name.

**Comment by antony-jr** [comment]
@luzpaz The latest version resolved everything you mentioned. Open a new issue if you feel something is missing.

![Screenshot_20191024_091447](https://user-images.githubusercontent.com/33930174/67451974-88ccb380-f63f-11e9-8400-7aadabae0eb9.png)

**Comment by antony-jr** [comment]
It turns out **Github** had a free API to parse their flavor of Markdown. It was easy as a post request with our Markdown in question. https://developer.github.com/v3/markdown/

**Comment by luzpaz** [comment]
Looks fantastic! Great job and tip! Do you know if hte appimage folks will integrate this ?

**Comment by antony-jr** [comment]
> Do you know if the appimage folks will integrate this ?

@luzpaz Do you mean the release notes? or the entire update window?
